# Generated by Django 5.0.3 on 2024-07-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_name', models.CharField(blank=True, max_length=30, null=True)),
                ('tax_type', models.CharField(choices=[('null', 'null'), ('normal', 'normal'), ('harmonized', 'harmonized'), ('compounded', 'compounded')], default='null', max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.country')),
            ],
        ),
    ]
